### PR TITLE
Added serf 0.8.0

### PR DESCRIPTION
**Pull request by atonse**
Homebrew does not let you specify versions for dependent brews
so when homebrew's serf was upgraded to 0.8.1, kong broke since
it expected serf 0.8.0. Pulling serf into the mashape/kong tap
ensures that all the dependent formulas for the kong formula are
going to predictably work.

This is required to fix https://github.com/Mashape/kong/issues/2070

### CODE REVIEW

**Comment by atonse** [comment]
If you need to verify, the contents of this file were just copied byte for byte from: https://raw.githubusercontent.com/Homebrew/homebrew-core/dc750ebb906b12282e435a732bfbccfbd4b7b45c/Formula/serf.rb

**Comment by thibaultcha** [comment]
Ironically we used to have this Serf Formula already in this repo in the past, because there indeed isn't a way to specify versions for dependencies :)

However, with the upcoming 0.10 release, the required Serf version will be 0.8.1. And shortly after, we shall remove such forward-compatibility enforcments in the Serf versions and allow for any version *above* 0.7 to be used. Only we'd recommend a 0.8.1, as it would be the officially supported version. This should avoid offloading on us the workload of having to maintain yet another Formula :)

**Comment by atonse** [comment]
@thibaultcha  Excellent! ETA on when 0.10 is coming out? I'll install the kong devel to start using this.

**Comment by thibaultcha** [comment]
0.10.0 is now out ;) 

Closing this as we'll be relaxing the versions checking, but keeping it in mind just in case. Thanks!

**Pull request closed without merging**
