### PR TITLE
Use local tree when installing luarocks

### PR DESCRIPTION
**Pull request by ulfmagnetics**
Fixes https://github.com/Mashape/homebrew-kong/issues/39

### CODE REVIEW

**Comment by thibaultcha** [comment]
I wouldn't be quite in favor of this change since when developing with Kong and using the Makefile, it is the system tree that will be used and not the local one. It might be more interesting to instead change the location of the system tree maybe?

**Comment by caledhwa** [comment]
Can we get this merged? Right now it looks like to me the `brew install` is unusable...

**Comment by thibaultcha** [comment]
Unfortunately I believe this fix is incomplete. It seems like the Kong Lua sources will now be in `~/.luarocks/share/lua/5.1`. However, when LuaJIT is compiled in the OpenResty formula, the default `LUA_PATH` is:
```
./?.lua;/usr/local/openresty/luajit/share/luajit-2.1.0-beta2/?.lua;/usr/local/share/lua/5.1/?.lua;/usr/local/share/lua/5.1/?/init.lua;/usr/local/openresty/luajit/share/lua/5.1/?.lua;/usr/local/openresty/luajit/share/lua/5.1/?/init.lua
```

Hence not taking the local Luarocks tree into account. I see 2 possible fixes for this:
- Extend the default `LUA_PATH` when compiling LuaJIT
- Patch `bin/kong` to use the `luarocks.loader` module and make the Lua VM LuaRocks-aware, hence able to load module from `~/.luarocks`.

**Comment by caledhwa** [comment]
Ahhh... I see that now.

**Comment by thibaultcha** [comment]
Replaced by #43

**Pull request closed without merging**
